name: Deploy

on:
  push:
    branches: main

jobs:
  Deploy:
    name: Deploy to EC2
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2 
      - name: Build & Deploy
        env:
            AWS: ${{ secrets.AWS }}
            AWS_HOST: ${{secrets.AWS_HOST}}
            AWS_USER: ${{secrets.AWS_USER}}
      
        run: |
          echo "$AWS" > AWS && chmod 600 AWS
          ssh -o StrictHostKeyChecking=no -i AWS ${AWS_USER}@${AWS_HOST} '
          echo "hello world"
